/*
 * hotmart-challenge
 * Especificação da API Hotmart Challenge
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bismarck@ufmg.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BuyerReturn
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-21T21:49:30.173Z")



public class BuyerReturn {
  @SerializedName("buyerCode")
  private Integer buyerCode = null;

  @SerializedName("buyer")
  private String buyer = null;

  public BuyerReturn buyerCode(Integer buyerCode) {
    this.buyerCode = buyerCode;
    return this;
  }

   /**
   * id do produto
   * @return buyerCode
  **/
  @ApiModelProperty(example = "1", value = "id do produto")
  public Integer getBuyerCode() {
    return buyerCode;
  }

  public void setBuyerCode(Integer buyerCode) {
    this.buyerCode = buyerCode;
  }

  public BuyerReturn buyer(String buyer) {
    this.buyer = buyer;
    return this;
  }

   /**
   * Nome do comprador
   * @return buyer
  **/
  @ApiModelProperty(example = "Nome do comprador", value = "Nome do comprador")
  public String getBuyer() {
    return buyer;
  }

  public void setBuyer(String buyer) {
    this.buyer = buyer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyerReturn buyerReturn = (BuyerReturn) o;
    return Objects.equals(this.buyerCode, buyerReturn.buyerCode) &&
        Objects.equals(this.buyer, buyerReturn.buyer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyerCode, buyer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyerReturn {\n");
    
    sb.append("    buyerCode: ").append(toIndentedString(buyerCode)).append("\n");
    sb.append("    buyer: ").append(toIndentedString(buyer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

