/*
 * hotmart-challenge
 * Especificação da API Hotmart Challenge
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bismarck@ufmg.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SalesReturn
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-21T21:49:30.173Z")



public class SalesReturn {
  @SerializedName("salesCode")
  private Integer salesCode = null;

  @SerializedName("salesMan")
  private String salesMan = null;

  @SerializedName("buyer")
  private String buyer = null;

  @SerializedName("product")
  private String product = null;

  public SalesReturn salesCode(Integer salesCode) {
    this.salesCode = salesCode;
    return this;
  }

   /**
   * id do vendas
   * @return salesCode
  **/
  @ApiModelProperty(example = "1", value = "id do vendas")
  public Integer getSalesCode() {
    return salesCode;
  }

  public void setSalesCode(Integer salesCode) {
    this.salesCode = salesCode;
  }

  public SalesReturn salesMan(String salesMan) {
    this.salesMan = salesMan;
    return this;
  }

   /**
   * Nome do vedendor
   * @return salesMan
  **/
  @ApiModelProperty(example = "Juliana", value = "Nome do vedendor")
  public String getSalesMan() {
    return salesMan;
  }

  public void setSalesMan(String salesMan) {
    this.salesMan = salesMan;
  }

  public SalesReturn buyer(String buyer) {
    this.buyer = buyer;
    return this;
  }

   /**
   * Nome do comprador produto
   * @return buyer
  **/
  @ApiModelProperty(example = "Bismarck", value = "Nome do comprador produto")
  public String getBuyer() {
    return buyer;
  }

  public void setBuyer(String buyer) {
    this.buyer = buyer;
  }

  public SalesReturn product(String product) {
    this.product = product;
    return this;
  }

   /**
   * Descrição do produto vendido
   * @return product
  **/
  @ApiModelProperty(example = "Gopro Hero 7", value = "Descrição do produto vendido")
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesReturn salesReturn = (SalesReturn) o;
    return Objects.equals(this.salesCode, salesReturn.salesCode) &&
        Objects.equals(this.salesMan, salesReturn.salesMan) &&
        Objects.equals(this.buyer, salesReturn.buyer) &&
        Objects.equals(this.product, salesReturn.product);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salesCode, salesMan, buyer, product);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesReturn {\n");
    
    sb.append("    salesCode: ").append(toIndentedString(salesCode)).append("\n");
    sb.append("    salesMan: ").append(toIndentedString(salesMan)).append("\n");
    sb.append("    buyer: ").append(toIndentedString(buyer)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

