/*
 * hotmart-challenge
 * API Hotmart Challenge
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bismarck@ufmg.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SalesManReturn
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T11:27:03.523Z")



public class SalesManReturn {
  @SerializedName("SalesManCode")
  private Integer salesManCode = null;

  @SerializedName("salesMan")
  private String salesMan = null;

  public SalesManReturn salesManCode(Integer salesManCode) {
    this.salesManCode = salesManCode;
    return this;
  }

   /**
   * id do vedendor
   * @return salesManCode
  **/
  @ApiModelProperty(example = "1", value = "id do vedendor")
  public Integer getSalesManCode() {
    return salesManCode;
  }

  public void setSalesManCode(Integer salesManCode) {
    this.salesManCode = salesManCode;
  }

  public SalesManReturn salesMan(String salesMan) {
    this.salesMan = salesMan;
    return this;
  }

   /**
   * Nome do vedendor
   * @return salesMan
  **/
  @ApiModelProperty(example = "Nome do vedendor", value = "Nome do vedendor")
  public String getSalesMan() {
    return salesMan;
  }

  public void setSalesMan(String salesMan) {
    this.salesMan = salesMan;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesManReturn salesManReturn = (SalesManReturn) o;
    return Objects.equals(this.salesManCode, salesManReturn.salesManCode) &&
        Objects.equals(this.salesMan, salesManReturn.salesMan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salesManCode, salesMan);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesManReturn {\n");
    
    sb.append("    salesManCode: ").append(toIndentedString(salesManCode)).append("\n");
    sb.append("    salesMan: ").append(toIndentedString(salesMan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

