/*
 * hotmart-challenge
 * API Hotmart Challenge
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bismarck@ufmg.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BuyerReturn;
import io.swagger.client.model.ErrorReturn;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BuyerApi
 */
@Ignore
public class BuyerApiTest {

    private final BuyerApi api = new BuyerApi();

    
    /**
     * Deletar comprador
     *
     * Deletar comprador
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletarCompradorTest() throws ApiException {
        Integer buyerCode = null;
        api.deletarComprador(buyerCode);

        // TODO: test validations
    }
    
    /**
     * Recupera a lista geral de comprador
     *
     * Recupera a lista de comprador
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConsultarCommpradorTest() throws ApiException {
        BuyerReturn response = api.getConsultarCommprador();

        // TODO: test validations
    }
    
    /**
     * Buscar informações do comprador especifico por id
     *
     * Buscar informações do comprador especifico por id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConsultarCompradorIdTest() throws ApiException {
        Integer buyerCode = null;
        BuyerReturn response = api.getConsultarCompradorId(buyerCode);

        // TODO: test validations
    }
    
    /**
     * Cadastro de comprador
     *
     * Cadastro de comprador
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCadastrarCompradorTest() throws ApiException {
        Integer buyerCode = null;
        String buyer = null;
        api.postCadastrarComprador(buyerCode, buyer);

        // TODO: test validations
    }
    
    /**
     * Alterar cadastro do comprador
     *
     * Alterar cadastro do comprador
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putAlterarCompradorTest() throws ApiException {
        Integer buyerCode = null;
        String buyer = null;
        api.putAlterarComprador(buyerCode, buyer);

        // TODO: test validations
    }
    
}
