/*
 * hotmart-challenge
 * API Hotmart Challenge
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bismarck@ufmg.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorReturn;
import io.swagger.client.model.SalesManReturn;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SalesmanApi
 */
@Ignore
public class SalesmanApiTest {

    private final SalesmanApi api = new SalesmanApi();

    
    /**
     * Deletar cadastro de vendedor
     *
     * Deletar produto
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletarVendedorTest() throws ApiException {
        Integer salesManCode = null;
        api.deletarVendedor(salesManCode);

        // TODO: test validations
    }
    
    /**
     * Recupera a lista geral de vendedores
     *
     * Recupera a lista de vendedores
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConsultarVendedorTest() throws ApiException {
        SalesManReturn response = api.getConsultarVendedor();

        // TODO: test validations
    }
    
    /**
     * Buscar informações cadastro de vendedor por id
     *
     * Buscar informações de produtos por id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConsultarVendedorIdTest() throws ApiException {
        Integer idSalesMan = null;
        SalesManReturn response = api.getConsultarVendedorId(idSalesMan);

        // TODO: test validations
    }
    
    /**
     * Salvar cadastro de vendedor
     *
     * Salvar cadastro de vendedor
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCadastrarVendedorTest() throws ApiException {
        Integer salesManCode = null;
        String salesMan = null;
        api.postCadastrarVendedor(salesManCode, salesMan);

        // TODO: test validations
    }
    
    /**
     * Alterar o cadastro de vendedor
     *
     * Alterar o cadastro de vendedor
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putAlterarVendedorTest() throws ApiException {
        Integer salesManCode = null;
        String salesMan = null;
        api.putAlterarVendedor(salesManCode, salesMan);

        // TODO: test validations
    }
    
}
